### ISSUE TITLE
Auto Retry retries when it should not

### ISSUE THREAD

**Issue by chris-rudmin** [ToothlessGear/node-gcm#145]
On 4xx client errors, it does not make sense to retry because our input is invalid. The server will reject with the same error if we try with the same input.

**Comment by hypesystem** [comment]
This is completely correct! It wouldn't be a breaking change, either. If you have the time, please make a PR for this :)

**Comment by eladnava** [comment]
@hypesystem The line has changed since then =(

A quick tip for next time when you want to link to a specific line in a file: Click it, then press `y` on your keyboard, and the browser will refresh with a `node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L95` which won't change as the `master` branch gets updated.

**Comment by hypesystem** [comment]
Cool :) The fix should probably be somewhere in here: https://github.com/ToothlessGear/node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L192-L199

**Comment by eladnava** [comment]
@hypesystem Currently, in the [lines you highlighted](https://github.com/ToothlessGear/node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L192-L199), we retry no matter what. I think we need to return a flag in `sendNoRetry` called `retry` that indicates whether we should retry the request or not, since there is no way to set that behavior right now.

In addition, we should not retry when we receive a `401 Unauthorized` status code in [sender.js#L118](https://github.com/ToothlessGear/node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L118).

**Comment by hypesystem** [comment]
Are there any other cases than `401` where we would not retry?

**Comment by eladnava** [comment]
@hypesystem Yes. Any 4xx is a client error and we should not retry.

**Comment by hypesystem** [comment]
The easy solution would then be to match the status code and not retry if it is a number `399 < x < 500`

**Comment by eladnava** [comment]
@hypesystem the `request` module returns the error code in a property,
wouldn't that be a cleaner solution than to perform a regular expression?
And then, return a `retry` flag to indicate whether to retry or not.

**Comment by hypesystem** [comment]
Matching on some set propery would be a cleaner solution, yes. But I think the responsibility for deciding whether or not we should retry should be in `send`, not `sendNoRetry`.

I think the solution with returning something useful (like a `retryableError` flag) would be an obvious part of #71 (Better error reporting).

**Comment by chris-rudmin** [comment]
While we reviewing the retry code, it might be a good idea to implement using the Retry-After header in 5xx error cases instead of configured backoff delay. Spec can be found here: https://developers.google.com/cloud-messaging/http-server-ref

**Comment by eladnava** [comment]
@chris-rudmin There is already an open issue about `Retry-After`, we should continue discussion on it in that issue.

**Comment by eladnava** [comment]
@hypesystem So should we just check if the `err` object is a number and in the 4xx range in [sender.js#L193](https://github.com/ToothlessGear/node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L193)?

**Comment by hypesystem** [comment]
@eladnava that is my suggestion :smile:

**Comment by eladnava** [comment]
@hypesystem Submitted the PR =)

**Comment by hypesystem** [comment]
Fixed in your PR @eladnava  :smile:
