### ISSUE TITLE
Compatibility documentation

### ISSUE THREAD

**Issue by hypesystem** [ToothlessGear/node-gcm#155]
We are getting a lot of questions, recently, that boil down to compatiblitiy: which client library is used, which things work with that library, etc.

We should consider writing something about compatibility, at least a section saying which client-sides we can verify as working.

**Comment by eladnava** [comment]
@hypesystem GCM client libraries? E.g. iOS/Android/Cordova/PhoneGap?

**Comment by hypesystem** [comment]
Exactly. Especially Cordova and PhoneGap seem problematic.

**Comment by eladnava** [comment]
@hypesystem Here's what I've gathered so far about compatibility issues as of 11/12/2015:

Phonegap / Cordova ([phonegap-push-plugin](https://github.com/phonegap/phonegap-plugin-push))
* [No support for subscribing to topics (GCM PubSub)](https://github.com/phonegap/phonegap-plugin-push/issues/79)
* [Must supply `data` object if sending a `notification`](https://github.com/phonegap/phonegap-plugin-push/issues/387)
* [Requirement for all 3 notification fields to be sent](https://github.com/ToothlessGear/node-gcm/issues/180)
* [~~Requires the title to be inside the `notification` object and the message to be set in the `data` object~~](https://github.com/phonegap/phonegap-plugin-push/issues/87#issuecomment-136233665) (Fixed in 1.2.1)

Couldn't find any issues for Ionic, though.

**Comment by hypesystem** [comment]
I think that pretty much covers it. I don't remember seeing any specific issues with Ionic.

I don't honestly know what the best way to document these things would be --- no matter what we would risk getting out of date very quickly, if we write something like "phonegap-push does not currently support topic subscription or using the `notification` field".

**Comment by eladnava** [comment]
@hypesystem Absolutely no problem there, we can just write it this way:

> As of the 1st of January, 2016, {fill-in-issue-here-with-hyperlink}

I'm thinking about adding it to the `README.md`, below **Custom GCM request options**.

**Comment by hypesystem** [comment]
Sure! Sounds good :smile:

**Comment by eladnava** [comment]
@hypesystem Submitted PR =)
