### ISSUE TITLE
GCM server

### ISSUE THREAD

**Issue by roccomuso** [ToothlessGear/node-gcm#206]
Wouldn't be useful to have also the possibility to start a server that listen and saves the users' Token?

**Comment by hypesystem** [comment]
It sure would! Unfortunately, in reality, there are many other requirements than just blindly saving users' requirements. Most app developers will want some sort of authentication or other vetting process of users claiming to be using their app.

A simple server like that would be great to have as an example implementation, though.

I am thinking it should probably be a separate project, using node-gcm on the inside. What do you think?

**Comment by roccomuso** [comment]
@hypesystem yeah definetly should be a new project, I can work on that, should I fork or create a new repo?

**Comment by hypesystem** [comment]
I think it sounds like a great opportunity for a new repository using node-gcm as a dependency :smile:

**Comment by roccomuso** [comment]
Working on it ;) I'll show you something soon.

**Comment by roccomuso** [comment]
@hypesystem 
I sticked to the original repo, so i thought better fork than create a whole new repo.
Check it out:
https://github.com/roccomuso/node-gcm

**Comment by hypesystem** [comment]
I am going to close this issue because it is not an issue with node-gcm.

It looks like a very interesting project, building a simple server for node-gcm.

I don't see any reason to fork from node-gcm, though --- all of your dependencies on node-gcm are using the public interface, so a wrapping project would be a neater solution imo: I think you should create a new repository specifically for the server :smile:

**Comment by roccomuso** [comment]
@hypesystem new repo done: https://github.com/roccomuso/gcm-server

**Comment by eladnava** [comment]
@roccomuso Good job! Looks pretty cool. Well done moving it to its own repo, I agree that it's better that way.

**Comment by hypesystem** [comment]
Looks good! :+1:
