### ISSUE TITLE
Log push notifications

### ISSUE THREAD

**Issue by harshalyeole-tudip** [ToothlessGear/node-gcm#283]
Is it possible to log push notifications sent using node-gcm?

**Comment by eladnava** [comment]
Hi @harshalyeole-tudip,
You can utilize at logging utility such as [bunyan](https://github.com/trentm/node-bunyan) and simply invoke it right after calling `sender.send()` when sending notifications with node-gcm.

Since this is not an issue with the project, I am closing this. Feel free to consult StackOverflow for additional help with this.

**Comment by harshalyeole-tudip** [comment]
Thank you @eladnava
