### ISSUE TITLE
Not working in proxy

### ISSUE THREAD

**Issue by mikkysati** [ToothlessGear/node-gcm#97]
I am using this behind proxy and have set the environment variables http_proxy and https_proxy. But whenever I try to run the server I get this error:

[Error: tunneling socket could not be established, cause=Parse Error] code: 'ECONNRESET'

**Comment by pablonazareno** [comment]
I'm having the same issue.
It's because in module dependencies, it not specify the version of request module very well.
And in latest releases of that module proxy configuration have change.
I'm working in a PR to fix this.

**Comment by mikkysati** [comment]
Nice so to use proxy, do I have to use this line of code?
var sender = new gcm.Sender('API KEY',{'proxy':'proxy:port'});

**Comment by pablonazareno** [comment]
Yes, but in my case this stop working when upgrade to latest version of node-gcm.
And I have to add another line to get work again, the one at Pull Request.

**Comment by mikkysati** [comment]
I tried that code(which is in your Pull Request), still gcm-node is not working.

**Comment by eladnava** [comment]
@pablonazareno @mikkysati I tracked down the source of the problem when supplying a `proxy` and found a solution.

### The Problem

1. On [sender.js#86](https://github.com/ToothlessGear/node-gcm/blob/e71405c812892b63b8d673f071874a515409c243/lib/sender.js#L86), we set a `Content-length` header. 
2. When setting proxy, `request` creates an `HTTP CONNECT` request through the proxy to establish a HTTPS tunnel, but sends the `Content-length` header along with this request, which is incorrect behavior. The result is that the GCM server is waiting for us to send data in the `CONNECT` request, when all we wanted to do was open an HTTPS tunnel:
![fail](https://cloud.githubusercontent.com/assets/4394189/11642704/0b99427e-9d48-11e5-97e9-cf01ddf123b2.png)

3. The GCM server responds with an error code.

This is caused by the following code, which constructs the `request`:

```js
    var post_options = {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'Content-length': Buffer.byteLength(requestBody, 'utf8'),
            'Authorization': 'key=' + this.key
        },
        uri: Constants.GCM_SEND_URI,
        body: requestBody
    };
```

Since we hard-coded the `Content-length` header, `request` sends it with every request, even the `CONNECT`.

### The Solution

The solution is to let `request` construct these headers when it's time by changing the way we configure the `request` as follows:

```js
    var post_options = {
        method: 'POST',
        headers: {
            'Authorization': 'key=' + this.key
        },
        uri: Constants.GCM_SEND_URI,
        json: JSON.parse(requestBody)
    };
```

The main difference is that we no longer hard-code the content headers, and supply the JSON payload in the `json` parameter.

I will submit a PR with this fix when I find some free time.

@hypesystem fyi.

**Comment by hypesystem** [comment]
Cool! Good spot, and will also make our integration with `request` easier.
